DATASET:
  EXP: True
  EXP_DIM: 64
  FRAME_LEN: 32
  COEFF_LEN: 73
  NUM_CLASSES: 46

MODEL:
  AUDIOENCODER:
    LEAKY_RELU: True
    NORM: 'IN'
  DISCRIMINATOR:
    LEAKY_RELU: False
    INPUT_CHANNELS: 6
  CVAE:
    AUDIO_EMB_IN_SIZE: 512
    AUDIO_EMB_OUT_SIZE: 6
    SEQ_LEN: 32
    LATENT_SIZE: 64
    ENCODER_LAYER_SIZES: [192, 128]
    DECODER_LAYER_SIZES: [128, 192]

TAG:
  NAME: cvae_UNET_useAudio_usewav2lipAudioEncoder


